# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Test Comment added from Git Hub - Check CI on AZ Pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

- task: Docker@2
  inputs:
    containerRegistry: 'Docker_Connection'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker_Connection'
    repository: 'knallamuthu91 / azdevops001'
    command: 'buildAndPush'
    Dockerfile: '**/AzureDockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker_Connection'
    command: 'logout'

